opt_in_rules:
  - comma
  - leading_whitespace

line_length: 200

disabled_rules:
  - unused_closure_parameter
  - empty_enum_arguments
  - function_parameter_count
  - function_body_length

excluded:
  - Carthage
  - Pods
  - fastlane
  - Build
  - .build
  - Pods/**
  - Quick-Bites/AppDelegate.swift
  - Quick-Bites/SceneDelegate.swift